
$/ = "--";
my $a = <DATA>;
my $b = <DATA>;

my @a = split /\n/, $a;
my @b = split /\n/, $b;

my %map = ();
for (@a) {
	my ($hex, $name, $uwp) = /^(\d\d\d\d) (.*?)\s*([ABCDEX]\w{6}-\w)/;
	$map{ $hex } = {
		hex => $hex,
		name => $name,
		uwpm0 => $uwp
	};
}

for (@b) {
	my ($hex, $name, $uwp) = /^(\d\d\d\d) (.*?)\s*([ABCDEX]\w{6}-\w)/;
	$map{ $hex }->{ uwpm1105 } = $uwp;
	$map{ $hex }->{ uwpm600  } = interpolate($map{$hex}->{ uwpm0 }, $uwp);
}

$/ = "\n";
open IN, 'core-m1105.sec' or die "Can't open core-m1105.sec\n";
for (<IN>)
{
	next unless /^\d\d\d\d /;
	chomp;

	my $hex     = substr($_, 0, 4);
	#my $name    = substr($_, 5, 20); 
	#my $uwp     = substr($_, 26, 9);
	my $bg      = substr($_, 108, 2);
	my $w       = substr($_, 111, 2);
	my $stellar = substr($_, 119);

	#print "$hex ($name) ($uwp) ($bg) ($w) ($stellar)\n";

	$map{ $hex }->{ bg } = $bg;
	$map{ $hex }->{ w  } = $w;
	$map{ $hex }->{ stellar } = $stellar;
}
close IN;

=pod
print<<EOHEADER;
Hex  Name                   M0          M600       M1105     
---- ---------------------  ---------   ---------  ---------
EOHEADER
=cut

print<<EOHEADER;
# Generated by Perl
# 2024-02-08

# Core
# 0,0

# Name: Core
# Name: Ukan (vi)

# Abbreviation: Core

# Milieu: M600

# Credits: Core sector was designed by Marc W. Miller and appears in Atlas of the Imperium (GDW, 1984).

# Source:    Traveller 5 Second Survey

# Subsector A: Apge
# Subsector B: Perite
# Subsector C: Ameros
# Subsector D: Shinkan
# Subsector E: Sanches
# Subsector F: Mekee
# Subsector G: Core
# Subsector H: Kaskii
# Subsector I: Bunkeria
# Subsector J: Cemplas
# Subsector K: Chant
# Subsector L: Dingtra
# Subsector M: Cadion
# Subsector N: Ch'naar
# Subsector O: Dunea
# Subsector P: Saregon

Hex  Name                 UWP       Remarks                               {Ix}   (Ex)    [Cx]   N     B  Z PBG W  A    Stellar        
---- -------------------- --------- ------------------------------------- ------ ------- ------ ----- -- - --- -- ---- ---------------
EOHEADER

foreach my $hex (sort keys %map) {
   next unless $hex;
   my $p = int(rand(9)+1);
   $p = 0 if $map{$hex}->{ uwpm600 } =~ /^....0/;

   printf "%04d %-20s %s %-70s $p%s %-2s      %s\n",
   		$hex, 
		$map{ $hex }->{ name }, 
		$map{ $hex }->{ uwpm600 },
		tradeCodes( $map{$hex}->{ uwpm600 } ),
		$map{ $hex }->{ bg },
   		$map{ $hex }->{ w },
		$map{ $hex }->{ stellar },
		;
=pod
   print "$hex ", sprintf("%-20s", $map{ $hex }->{ name }), 
   			"\t", $map{ $hex }->{ uwpm0 }, 
			"\t", $map{ $hex }->{ uwpm600 }, 
			"\t", $map{ $hex }->{ uwpm1105 }, 
			"\n";
=cut
}

sub interpolate
{
	my ($uwpm0, $uwpm1105) = @_;
	my @uwpm0    = split '', $uwpm0;
	my @uwpm1105 = split '', $uwpm1105;
    my @uwpm600  = qw/X 0 0 0 0 0 0 - 0/;

	# interpolate the starport...
	my $starport = int((hex($uwpm0[0]) + hex($uwpm1105[0]))/2);
	$uwpm600[0] = sprintf("%X", $starport);

    # copy the physical stats
	@uwpm600[1..3] = @uwpm1105[1..3];

	# interpolate the population...
	my $pop = int((hex($uwpm0[4]) + hex($uwpm1105[4]))/2);
	$uwpm600[4] = sprintf("%X", $pop);

	my $gov = roll($pop);
	$gov = 0 if $pop == 0;
	$gov = 7 if $gov == 6;
	$uwpm600[5] = sprintf("%X", $gov);

    my $law = roll($gov);
	$law = 0 if $pop == 0;
	$uwpm600[6] = sprintf("%X", $law);

    # [7] is the dash
	$uwpm600[7] = '-';

	# interpolate the TL...
	my $tl = int((hex($uwpm0[8]) + hex($uwpm1105[8]))/2);
	$uwpm600[8] = sprintf("%X", $tl);

    my $uwp = join '', @uwpm600;
	#print "($uwp)\n";
	return $uwp;
}

sub roll 
{
	my $value = shift;
	$value += int(rand(6)) - int(rand(6));
	$value = 0 if $value < 0;
	$value = 15 if $value > 15; # whoof.
	return $value;
}

###############################################################################
#
#   Rebuild Trade Codes.
#
###############################################################################
sub tradeCodes
{
   my $uwp   = shift;
   my $zone  = shift || '';
   my $mainworldType = shift || '';
   my $hz    = shift || 0; # i.e. in the HZ
   my $orbit = shift || 3; # safe guess

   print STDERR "** ERROR ** tradeCodes() requires a UWP, not a worldref!\n" unless $uwp =~ /\w{6}-\w/;

   my @codes;
   push @codes, 'Ag' if $uwp =~ /..[4-9][4-8][5-7]..-./;
   push @codes, 'As' if $uwp =~ /.000...-./;
   push @codes, 'Ba' if $uwp =~ /....000-0/;
   push @codes, 'Cy' if $uwp =~ /....[5-9A]6[0-3]-./;
   push @codes, 'De' if $uwp =~ /..[2-9]0...-./;
   push @codes, 'Di' if $uwp =~ /....000-[^0]/;
   push @codes, 'Fl' if $uwp =~ /..[ABC][1-9A]...-./;
   push @codes, 'Ga' if $uwp =~ /.[678][568][567]...-./;
   push @codes, 'He' if $uwp =~ /.[3-9ABC][2479ABC][012]...-./;
   push @codes, 'Hi' if $uwp =~ /....[9ABCDEF]..-./;
   push @codes, 'Ic' if $uwp =~ /..[01][1-9A]...-./;
   push @codes, 'In' if $uwp =~ /..[012479ABC].[9ABCDEF]..-./;
   push @codes, 'Lo' if $uwp =~ /....[123]..-./;
   push @codes, 'Na' if $uwp =~ /..[0-3][0-3][6-9ABCDEF]..-./;
   push @codes, 'Ni' if $uwp =~ /....[456]..-./;
   push @codes, 'Oc' if $uwp =~ /.[ABCDEF][^012]A...-./;
   push @codes, 'Pa' if $uwp =~ /..[4-9][4-8][48]..-./;
   push @codes, 'Ph' if $uwp =~ /....8..-./;
   push @codes, 'Pi' if $uwp =~ /..[012479].[78]..-./;
   push @codes, 'Po' if $uwp =~ /..[2-5][0-3]...-./;
   push @codes, 'Pr' if $uwp =~ /..[68].[59]..-./;
   push @codes, 'Px' if $uwp =~ /..[23AB][1-5][3-6].[6-9]-./;
   push @codes, 'Re' if $uwp =~ /....[0-4]6[045]-./;
   push @codes, 'Ri' if $uwp =~ /..[68].[6-8]..-./;
   push @codes, 'Va' if $uwp =~ /..0....-./;
   push @codes, 'Wa' if $uwp =~ /.[3-9][3-9DEF]A...-./;
  
   #push @codes, 'Mr' if $uwp =~ /.....6.-./ && ! grep( /Px|Re|Pe/, @codes );

   push @codes, 'Fr' if $uwp =~ /.[2-9].[1-9A]...-./ && $hz >= 2;
   push @codes, 'Ho' if $hz < 0;
   push @codes, 'Co' if $hz > 0;
   push @codes, 'Lk' if $mainworldType eq 'Close Satellite';
   push @codes, 'Tr' if $uwp =~ /.[6-9][4-9][3-7]...-./ && $hz == -1;
   push @codes, 'Tu' if $uwp =~ /.[6-9][4-9][3-7]...-./ && $hz == 1;
   push @codes, 'Tz' if $orbit == 0 || $orbit == 1;

   push @codes, 'Sa' if $mainworldType =~ /Satellite/
                     && $mainworldType ne 'Close Satellite';

   push @codes, 'Fo' if $zone eq 'R';
   push @codes, 'Pz' if $uwp =~ /....[789ABCDEF]..-./ && $zone eq 'A';
   push @codes, 'Da' if $uwp =~ /....[0-6]..-./    && $zone eq 'A';

   return join ' ', @codes;
}

sub calcSubsectorLetter
{
	my $hex = shift;
	my @ss = 'A'..'P'; # 0..15
	my ($col, $row) = $hex =~ /(..)(..)/;
	$col = int(($col-1)/8);
	$row = int(($row-1)/10);
	return $ss[ int($col) + 4 * int($row) ];
}


__DATA__
0103 Irkigkhan            D9C4599-6           
0104 Shana Ma             E551000-6           
0106 Niir                 B9C68AA-7           
0202 Isheg Nuuruup        B8476B9-A           
0203 Khaur Ga             C434533-B           
0208 Gekshiiuun           D527200-4           
0210 Uras                 A797888-A           
0302 Khaam                C597000-7           
0304 Kuunaa               B8B5000-9           
0305 Muudeshi             B100AAA-B           
0306 Kiid                 C786000-7           
0307 Pasliir              B574444-7           
0308 Shar                 C688111-7           
0310 Mag                  E888000-3           
0402 Apge                 B772555-D           
0403 Irli Un              B000144-B           
0405 Dake Ag              C674000-8           
0408 Arkag Ka             C5536BB-9           
0409 Gin                  C994311-8           
0410 Daa                  B779133-9           
0502 Niir                 B76A5AA-9           
0505 Emiigaap             C430688-9           
0603 Dashgad              C540244-B           
0606 Khuumiam             C736788-7           
0707 Maaruur              E692000-6           
0806 Gaage                A312533-C           
0808 Kikim                D575000-2           
0901 Karnika              C755968-9
0903 Dis                  E000000-6           
0905 Shazeku              B553ADD-A           
0906 Muumuu               C7766AA-9           
0907 Gish                 C778733-6           
0910 Gisid                E567000-2           
1002 Mishaar              B540544-C           
1008 Uusla                C302422-B           
1009 Luumiiliiplen        B536433-9           
1101 Kiimi Di             E420000-7           
1102 Gipirkash            C594122-8           
1104 Rae                  E580544-3           
1108 Uurruu E             B7657AA-7           
1109 Uuruun Kuu           D987000-5           
1202 Kargi                C569411-9           
1204 Limashimii           C547000-9           
1205 Miilapkhas           B590477-7           
1302 Uumaad Nurir         C778000-8           
1307 Ashduuma             C88A6AA-8           
1308 Akpussagna           E557000-2           
1309 Uuniluu              B94A566-9           
1403 Gag                  E896000-3           
1407 Imguu                B200499-9           
1410 Uurgin               C310599-7           
1503 Zepdind Ir           C5368AA-5           
1505 Kuum                 C667100-6           
1506 Kakaaguur            C586000-5           
1508 Asmi                 D697222-3           
1510 Kinuu                E310366-7           
1605 Giiar E              B546244-A           
1609 Sirma                C4249A7-A           
1610 Nagan                C645144-9           
1701 Kama                 E99A455-6           
1702 Iski Kuu             D563000-5           
1703 Irkhiide             C645300-A           
1707 Erdi                 C6866AA-6           
1708 Uunnagirluu          B000444-9           
1710 Kherip Ag            E000000-6           
1801 Kind                 E551000-3           
1808 Gamgiigela           B1008BB-A           
1901 Zaniin               B694588-8           
1902 Irbi                 B889000-8           
1909 Iiska Ashgi          D433000-4           
2006 Amur Isark           B310788-7           
2008 Khekaa               A310122-C           
2010 Maashsha             C8B7000-A           
2101 Khizuuuum            A85A433-C           
2102 Ravla                B554211-7           
2103 Inlun Ra             E000000-6           
2104 Nuudle               C884877-7           
2105 Shiza                C561866-A           
2203 Andkag Pa            B438000-A           
2205 Daash                C538655-A           
2206 Edirkisdii           B544100-A           
2209 Nimluin              A576AAA-C           
2210 Gis                  D562466-3           
2306 Erem Dash            D645333-7           
2401 Erkiim               A52A111-B           
2403 Aaruu Zi             B569322-8           
2404 Gemi                 C400000-A           
2405 Luunni Miu           C576000-5           
2407 Lagaashin            E767344-3           
2408 Arnaki               A200988-C           
2410 Uungip               C000577-9           
2501 Erani                B000699-B           
2503 Gigi                 C000000-A           
2507 Ninnund              A986699-9           
2602 Gasa Kuu             B544200-8           
2603 Arunde               EAAA233-7           
2606 Margish Liir         C547244-A           
2608 Duur                 B557377-6           
2609 Bambe                C599300-B           
2610 Kerliar              C5949BB-7           
2703 Derku                C611A99-A           
2705 Uundiirshiikis       E556000-5           
2706 Sinmig               C564455-A           
2707 Kalanaauud           D525000-6           
2709 Kimvle               A000666-C           
2802 Gekhuu               B678566-B           
2803 Kersi Am             B427555-8           
2904 Ishnuunar            E572533-3           
2906 Damki Im             B200ABB-9           
2910 Shusa Liishli        C311000-B           
3002 Isuur                C544300-7           
3003 Iidsha               C665000-8           
3005 Aarza Kand           C304644-8           
3008 Mim                  A400466-B           
3101 Edza                 B73A000-A           
3103 Gar                  B439688-B           
3104 Aadkha Na            E200122-6           
3105 Kir                  C300544-B           
3106 Uumuurler            B425222-9           
3203 Maain                D668533-4           
3205 Iidshuu              C765355-6           
3206 Dim                  D646266-6           
3207 Imkhag Guu           D567366-4           
3208 Agduu                E400000-8           
3210 Kamnakiiaar          A965455-A           
0112 Per                  B673111-9           
0113 Khishi               D798000-8           
0114 Khid                 C550244-9           
0116 Idpuu                B585755-8           
0117 Neki                 C664522-6           
0120 Kein                 C544544-8           
0212 Gir                  B645411-8           
0216 Emuuis               C422100-A           
0218 Darnii Kimi          D878111-4           
0220 Inir                 E88A000-5           
0313 Maish Akush          C432666-9           
0314 Maarshigervlig       B8A5455-8           
0315 Das                  B685366-8           
0316 Dudin                D5286BB-9           
0319 Uurze                B434000-B           
0411 Kash                 E584000-4           
0414 Shiieniaand          D561133-3           
0416 Sanches              B654844-B           
0418 Shardi               E433744-7           
0420 Nirgem               C6A7000-8           
0511 Gaadir               D586344-A           
0512 Arla Un              D5137BB-4           
0513 Kaman                E772000-3           
0516 Rundan               C76A522-7           
0517 Shiga Sha            A726133-A           
0519 Zan                  C100266-B           
0612 Khukhi               C667788-7           
0619 Iggaar               B758766-7           
0713 Ruuni                C433500-A           
0714 Kiishad              B6A7999-8           
0718 Uupig                D797244-4           
0811 Alekvadin            B675977-A           
0812 Kakhu Gash           B845755-A           
0816 Keshi                C792566-8           
0820 Iruukzi              C776000-6           
0911 Kiked Iig            C545311-7           
0915 Mupisar              B577000-B           
0916 Irshiish             C95A344-9           
0919 Marpi Ka             D550000-6           
1012 Uurmu Kuu            C424100-B           
1016 Urshra               B561755-B           
1019 Liga Ka              C783000-8           
1112 Kish                 D310111-7           
1114 Adguu Uun            A5206AA-9           
1116 Vlaagesh Iirki       B783422-6           
1120 Shuunkha             C540666-9           
1214 Guun                 E585000-4           
1219 Amed                 C310533-9           
1220 Aruu                 C100000-A           
1314 Mukirurguum          B859000-8           
1316 Shiirand             D85A477-4           
1317 Gipkikhar            C203322-B           
1320 Adkaash              B422000-9           
1416 Imdi Mi              B68A000-8           
1418 Kishdush             D646000-5           
1511 Aman Urk             E545300-4           
1512 Ansham               B8C3122-7           
1518 Uugnii               A86A533-C           
1519 Sher                 D9D4322-5           
1611 Shauug               B964255-A           
1615 Marlakasi            E779000-0           
1616 Vluurvlash           E9B4000-0           
1711 Kaakhe Mirir         D100533-7           
1713 Uushnem              C9D4511-7           
1715 Irur Gir             C581000-1           
1717 Kasdaga              D9B7444-7           
1812 Khiidkar             B583688-9           
1813 Gaadvlu Ki           E554544-3           
1815 Unrair               C510111-7           
1819 Unkuu                B505144-8           
1912 Khamiila             A430300-C           
1916 Irurk                A544644-9           
1917 Aggii Ganaan         E422417-4           
1918 Irmap Muu            C624422-7           
1919 Nirinirk             E776000-6           
1920 Kuma As              D410000-1           
2011 Kikamaa              D544000-4           
2012 Biin                 E651233-4           
2014 Bala                 C62A333-8           
2016 Zuarkri              C877599-8           
2017 Kain                 E576244-4           
2020 Kan                  D200000-1           
2111 Kiikagaiir           C546455-9           
2112 Nappar               C428255-7           
2115 Zimiin               A431744-B           
2118 Sylea                A586A98-C           
2211 Gid                  B655555-B           
2213 Kiirri               B541000-5           
2214 Lauursha             E849555-6           
2216 Khash                B8A6000-7           
2218 Shaaak               B436999-9           
2219 Ase                  B420488-C           
2220 Khishnar             E562255-0           
2312 Giikkala             B79A755-B           
2314 Laairer              B559111-8           
2316 Idmum                C5447AA-7           
2317 Gikuu                E571344-1           
2318 Kuunen Ish           B310666-8           
2319 Ipduu In             D979577-7           
2320 Uunli                B6B5000-2           
2413 Kiur                 E651000-0           
2414 Khaashuu             AA7A344-8           
2416 Argash               B755400-6           
2419 Gash                 E544000-0           
2511 Kuuir Am             D577333-6           
2513 Girku                E89A000-1           
2517 Imaar Pa             D544000-1           
2519 Riiiid Irman         E000133-7           
2611 Kishkeiim            C201422-8           
2615 Ispumer              E581855-5           
2616 Likhamii             B536788-6           
2720 Lir                  B426100-9           
2814 Muugkha              D423133-6           
2816 Indshiim Ganme       B869588-A           
2912 Leer                 B7B3244-A           
2913 Khiuur La            C8B3200-4           
2914 Mikhag Kuu           B668799-7           
2916 Khiinra Ash          CAE6133-6           
3011 Laudum               B552ADD-9           
3015 Anuug                C783000-7           
3019 Kinekesh             C422100-B           
3113 Urir Gug             E542755-4           
3115 Markasher            E100300-5           
3117 Khiiir               B200533-9           
3118 Lemik                C56A722-A           
3211 Zikhi                D427211-9           
3216 Shand                C964111-7           
3218 Kaskii               B300766-E           
0125 Larsaluu             B664133-9           
0126 Danke Es             B541644-8           
0127 Emshi                B578733-8           
0128 Sheki                C559344-9           
0129 Laslii Mii           B984000-7           
0130 Siiaash              E200688-7           
0221 Kan                  B789588-A           
0222 Arir Ash             E310366-5           
0224 Lindbar              E434000-5           
0228 Ashder               C565000-7           
0322 Enluur               B542000-B           
0324 Vliga                B413000-8           
0325 Muuidimu             B310777-9           
0326 Dindma Eshgi         B540000-9           
0328 Baamlaa Maa          C553277-9           
0421 Murda                B887211-B           
0423 Gig                  B400322-B           
0428 Irlu                 C5358AA-B           
0429 Diid                 C9B9000-8           
0522 Amkhiikhaki          E562755-5           
0523 Uniimvlu             B590100-9           
0526 Uumkhi               B200000-A           
0527 Urguu                A557000-9           
0529 Iirkaa Gaasar        B586666-9           
0530 Mien Puuruu          D433322-5           
0622 Uurgigi              B647488-B           
0624 Giirud               A100266-C           
0721 Shika                E551466-6           
0722 Kuuda I              B561333-8           
0725 Khag                 C411266-A           
0727 Dral                 C7288DD-A           
0821 Lakhia               B000411-C           
0822 Siirduu              C540366-9           
0827 Iirla                B550444-A           
0921 Umda                 E6A7422-4           
0922 Guba Ak              B575000-C           
0929 Sheduu               E649000-6           
1022 Kaplir               E573544-4           
1023 Irkkha               B423688-9           
1028 Miim                 C550222-6           
1123 Guuirk               A100000-D           
1124 Imkhasham            A8AA677-C           
1125 Ishiira              D652100-6           
1129 Aruur                D6A4000-6           
1130 Merkaakhu            D79A355-A           
1221 Shuukha Zuush        BAD5100-7           
1222 Armi                 C577633-6           
1223 Muguu                D556000-5           
1225 Irmi Khi             E541666-4           
1226 Shanii Arduu         B585000-A           
1228 Lishiruud            B697311-6           
1229 Bais Si              E554133-3           
1321 Nuur                 B664100-6           
1322 Liper                C675AEE-7           
1323 Kushur Naa           B310200-C           
1328 Sar                  B647799-9           
1330 Shidkar              B685200-6           
1421 Angar                B436766-8           
1422 Ashbikuu             C7C2000-7           
1424 Khusgurlu            B652566-9           
1428 Vlaarvla Akha        A656544-9           
1430 Uukzi Giish          B100000-B           
1522 Gaashi Ash           C7C2133-7           
1523 Laus                 A596122-A           
1524 Shibashliim          A626A88-C           
1526 Gikakhii             E403211-6           
1529 Niin                 D310000-6           
1530 Arvli Khaan          B563000-9           
1622 Genkaaa              C420555-A           
1623 Aggaa Irpu           A567122-7           
1625 Gakirvli             C885333-7           
1628 Amshakshe            C633655-8           
1630 Kuusuu Uur           C430377-B           
1721 Duusikiim            C565555-8           
1724 Guurma Sa            A675322-A           
1725 Angairkshak          B545788-8           
1726 Demla                C000233-9           
1727 Khirar               B8B3111-A           
1730 Laik Girkki          BAB5499-8           
1821 Shar                 B78A200-D           
1822 Anga Ke              B200544-C           
1823 Gerar Khashii        E8B7000-4           
1824 Likamish             E554100-3           
1825 Rarkan               C5A2000-9           
1829 Shis                 B311655-A           
1921 Medishvlaas          C545377-7           
1924 Mar                  E555000-3           
1925 Naauup Emrim         A585617-9           
1927 Khiri                B94A222-6           
1929 Shakiisiir           E628311-4           
1930 Kegi And             B000788-C           
2021 Shaashsha            A300433-B           
2027 Amuum Kuu            C9A5444-9           
2028 Iipshimun            B543200-A           
2030 Ragni                E63A766-6           
2121 Vlaakier             B98A577-8           
2122 Iirkkhu              C576000-9           
2125 Urish                B5247CC-A           
2130 Iruies               B565000-9           
2221 Miium                C998271-6           
2222 Miiidkhig            C855899-8           
2223 Muun                 A866000-8           
2224 Kuula Iish           B560322-B           
2225 Duur                 C512111-9           
2226 Skeen                B591A88-C           
2227 Lider                C557100-6           
2322 Shusa                B581899-A           
2323 Lezaar               B423A88-8           
2326 Limeshuurgi          E410000-4           
2327 Riias                B759344-A           
2330 Raami                C522966-B           
2422 Geiish               B573000-B           
2425 Diki Shi             C200ABB-A           
2429 Arka Uum             B552222-6           
2521 Shipashuua           E560000-4           
2524 Gimuur Luu           B576000-8           
2526 Kisa                 A7C6000-C           
2529 Daa                  E564699-3           
2623 Gurdaan              B310633-B           
2624 Idas                 A592311-C           
2625 Imsha                B424122-A           
2628 Gashkanan            B74A255-8           
2630 Shesh                C000100-A           
2721 Khuuda               B551255-6           
2729 Gaar                 C560211-A           
2730 Maan                 B541466-B           
2821 Uuggarkirber         C552566-6           
2823 Muumi                D553300-9           
2825 Bishaakuuka          C683455-6           
2829 Gishashum            E100433-8           
2830 Navlaand Sha         EAC7111-5           
2922 Ekugush              B652699-7           
2924 Uushba Sind          D564888-2           
2928 Vlaki Khuu           A594588-B           
2929 Danuuvlan            B000000-A           
3021 Kamsii               A557666-8           
3022 Gurishi              B756677-9           
3025 Manluushagi          D200000-8           
3026 Uumkishla            C563100-6           
3027 Guuza Bem            C9D5322-6           
3028 Duuguu               A573244-C           
3121 Kagash               D554877-4           
3123 Kankuup Ir           B424AFF-8           
3125 Kadushii             E695ADD-5           
3127 Arkadkhi             C779233-A           
3128 Mish                 C679A88-9           
3129 Keras Vla            B867322-7           
3130 Agdam Gii            B5577CC-9           
3226 Duuka                B686955-A           
3227 Ashash As            B758255-7           
0132 Lash                 C76A355-B           
0133 Pumuuda              C8D7371-9           
0134 Miise                C421311-8           
0135 Maish Uun            C667111-9           
0138 Ziris                B873000-8           
0139 Shardir Aagkuug      C87A222-A           
0140 Aadkhien             E100000-7           
0231 Giuum Gim            E869000-4           
0234 Sishar               B667733-8           
0236 Gasha Uusar          D671455-6           
0240 Bur                  C587000-8           
0331 Guuriir              E100144-6           
0332 Mige Ris             B6557CC-8           
0334 Irka                 B999611-B           
0338 Kiimaa               C887000-7           
0431 Gizar Ik             B634200-9           
0432 Khiieshirk           C550744-B           
0437 Uumaamuushgii        C400799-A           
0439 Indand               B310000-A           
0440 Ganshas              A53A966-C           
0531 Dauur                B655100-8           
0537 Lia                  E654755-6           
0635 Anemzaa              B642422-7           
0637 Vlimas               C796000-5           
0731 Zzugep               C553AAA-9           
0734 Ferré                C797355-4           
0735 Aapas Mi             E584366-2           
0737 Shash                C898522-6           
0831 Kuuki Zaa            D549000-7           
0835 Laaze                D438000-4           
0839 Night                B5748CC-B           
0931 Siniir Sa            A599300-A           
0933 Kis                  B88A300-9           
1033 Geam                 C556000-9           
1034 Gur                  D533688-4           
1035 Madalagaa            B581233-8           
1037 Nuukhish             D542355-5           
1038 Maur Na              B558433-9           
1040 Davla                C528000-A           
1134 Aursis               A545522-B           
1140 Kaamind              CAF5511-8           
1232 Diam Kani            C430000-B           
1233 Laap                 B575000-9           
1236 Iipgiir              C591355-B           
1237 Miikuu Ar            E6A7355-4           
1239 Iirbasur             C547877-8           
1240 Lam                  D423000-7           
1334 Anshar               BACA000-B           
1335 Umkashuu             C554999-9           
1336 Kuka                 EA97000-2           
1338 Rid                  C695133-8           
1431 Saar                 C594000-6           
1434 Diirmuu              D755000-8           
1436 Arvlesaaish          E6B1000-5           
1437 Mishaa               B9A8100-7           
1440 Minduun Sammad       A58A411-C           
1531 Emsha I              C4339CC-8           
1533 Zagi Uu              C647255-6           
1534 Gid                  B76A533-B           
1536 Shueshlar            D435266-7           
1538 Uurme                A543211-9           
1539 Dimanaam             A583355-C           
1633 Reshi Uun            C300877-9           
1635 Khasherliguu         D627599-7           
1638 Malaaash             E759122-3           
1732 Maasaanin            C758322-9           
1733 Riid                 B865133-8           
1736 Mished               B4208A7-C           
1737 Irkhar Kirk          C574466-8           
1738 Ginna                C8A6000-8           
1739 Enshuuar             B6A6300-8           
1831 Irkgiur              C663422-4           
1833 Shaaram              E564100-5           
1836 Khea                 C5409BB-B           
1837 Anlumir              BA9A355-B           
1838 Iraddii              E989366-4           
1839 Rili Aash            B782411-7           
1840 Saruumdiiush         E743655-3           
1933 Uushruu              C599322-9           
1934 Zishma Kha           C886233-5           
1938 Keshi                B566200-7           
1940 Nii                  B548A88-8           
2034 Daindkhara           C424355-B           
2036 Uundi Zi             A410977-C           
2037 Daaud Urle           C433344-9           
2038 Gimmi Uussha         C576333-A           
2040 Gikhii Iis           A540511-8           
2133 Degkak Uun           E88A455-5           
2135 Diliig               D749000-4           
2136 Kiir                 A77A000-D           
2138 Adkhi                E888244-3           
2139 Nig                  C565344-9           
2140 Sidzer               D200255-8           
2232 Kuuma                C538255-8           
2237 Miregzi              B203266-9           
2334 Busirkher            B433000-A           
2335 Gish                 B555388-9           
2336 Adan                 D661411-3           
2338 Shinzarkan           B555211-9           
2431 Kim                  D7A8333-3           
2433 Uumad                D794400-5           
2435 Iidkek               BAB5333-7           
2437 Ligmuu               E636422-4           
2439 Inmaeg               B584000-8           
2532 Mie Uur              C310333-A           
2534 Mid                  C648222-5           
2536 Duunpigamuur         D511766-7           
2538 Duuind               B768344-8           
2540 Uumda                C553100-6           
2631 Uurkuumluu           B545000-8           
2635 Arvlaa Gam           E889377-3           
2636 Vled                 C998200-8           
2639 Suuashuur            C100100-B           
2640 Dishadshii           B614ACC-C           
2731 Miip                 C631000-8           
2732 Uurkhir              C9E7000-A           
2736 Gaen Luum            C424366-9           
2832 Sinad                C558744-A           
2836 Khuir                B578ABB-9           
2837 Igla                 B414555-D           
2839 Gaeshme              C783000-6           
2840 Gumir Gaeg           B8C37BB-8           
2931 Dinenruum            E432644-3           
2933 Ganad                A656A99-B           
2934 Dishe                A778000-A           
2935 Amuur Keiir          C572100-7           
2936 Saregon              A584522-C           
2937 Uurigger             C4347BB-8           
2938 Shakiiga             C867844-9           
3033 Ashmelam             A424633-D           
3034 Iishaanka            B554977-A           
3037 Lashupii             E665100-4           
3039 Kiiguuga             B8B4200-A           
3040 Unlakhar             A629733-C           
3131 Ashga                A7C3422-A           
3132 Kiir                 C562000-9           
3133 Nin                  C562233-5           
3135 Arla                 B58A688-8           
3137 Iimdii               C593000-7           
3140 Kerumirgaa           A562222-8           
3234 Gau                  C433666-B           
3235 Daii                 C75A100-8           
3238 Luushdeam            E560100-3           
--
0103 Irkigkhan            C9C4733-9
0104 Shana Ma             E551112-7
0106 Niizediju            B9C6886-A
0202 Azimuth              B847427-B
0203 Khaur Ga             B434314-D
0208 Gekshiiuun           D527524-8
0210 Uras                 A797679-C
0302 Khaam                B597488-A
0304 Kuunaa               B8B5364-C
0305 Muudeshi             A1008A8-E
0306 Kiid                 C786587-9
0307 Pasliir              B574763-A
0308 Shar                 B688226-B
0310 Mag                  E888341-6
0402 Apge                 A772A97-F
0403 Irli Un              B000200-E
0405 Dake Ag              C674567-9
0408 Arkag Ka             B553975-C
0409 Gin                  B994443-B
0410 Castell              B7795AF-C
0502 Niir                 B76A304-C
0505 Trokusian            B4306AE-B
0603 Dashgad              B540103-C
0606 Khuumiam             C736757-A
0707 Maaruur              E692110-7
0806 Sabsee               A312531-F
0808 Kikim                D575434-5
0901 Karnika              A755976-C
0903 Disal                E000300-9
0905 Shazeku              B553A88-E
0906 Muumuu               B77659D-B
0907 Gish                 B778787-A
0910 Tinea-Fabre          D567225-5
1002 Mishaar              B540AA8-E
1008 Uusla                B302301-E
1009 Luumiiliiplen        B536488-C
1101 Kiimi Di             D420233-9
1102 Girikash             B594344-B
1104 Rae                  E580859-7
1108 Uumeaxan             B765995-C
1109 Uuruun Kuu           C987346-8
1202 Kargi                B569751-C
1204 Limashimii           B547547-B
1205 Miilap Kas           B590886-A
1302 Uumaad Nurir         B778577-B
1307 Ashduuma             C88A653-B
1308 Akussanja            D557613-6
1309 Uuniluu              B94A432-C
1403 Gakxaal              E896200-7
1407 Imguu                B200320-C
1410 Uurgin               B31069C-A
1503 Zektind Ir           C536831-8
1505 Kuum                 B667646-9
1506 Kakaaguur            C586896-8
1508 Asmi                 D697226-5
1510 Kinuu                E310232-9
1605 Giiakiis E           A546445-D
1609 Sirma                C42498A-C
1610 Nagan                B645623-A
1701 Kama                 E99A489-9
1702 Iski Kuu             C5638B6-8
1703 Irkhedi              B645367-B
1707 Erdi                 B686845-A
1708 Unnagilu             B000868-C
1710 Kherip Ag            E000230-9
1801 Kinned               D551588-6
1808 Gamiigela            B100544-E
1901 Zaniin               B6945AB-B
1902 Irbi                 B88958A-C
1909 Iiska Ashgi          D433541-7
2006 Amur Isark           B310867-A
2008 Ameros               B310542-D
2010 Mashaa               B8B7496-C
2101 Khizuun              A85A79D-E
2102 Ravla                B554340-9
2103 Inlun Ra             E000127-A
2104 Nuudle               B884969-C
2105 Shiza                B561542-B
2203 Andkag Pa            B438441-D
2205 Daash                B538545-C
2206 Edirkisdii           B544310-B
2209 Nimluin              B576A65-E
2210 Gis                  C562867-6
2306 Erem Dash            C645441-9
2401 Erkiim               A52A231-D
2403 Aaruu Zi             B5699C9-A
2404 Gemi                 B400442-D
2405 Luunni Miu           C576342-9
2407 Lagaashin            E767764-6
2408 Arnaki               A200524-F
2410 Uungip               B000531-C
2501 Erani                B000556-F
2503 Gigi                 B000100-D
2507 Ninua                A9868BC-C
2602 Sagaku               B5447AA-A
2603 Arunde               EAAA303-B
2606 Margish Liir         B547431-B
2608 Dureija              B557999-9
2609 Ebba                 B599313-C
2610 Kerliar              B594769-A
2703 Derku                C611989-B
2705 Roska                E556200-8
2706 Sekwon               B564500-C
2707 Kalendae             C525340-9
2709 Kimvle               B000203-F
2802 Gekhuu               B678996-C
2803 Kersi Am             A427456-E
2904 Ishnuunar            D572944-7
2906 Damki Im             B200878-C
2910 Shusa Liishli        B311112-D
3002 Isuur                C544886-8
3003 Iidsha               B665455-B
3005 Aarza Kand           B304842-C
3008 Minos                A4007B9-E
3101 Edza                 B73A146-D
3103 Garen                B439568-E
3104 Aadkha Na            E200776-8
3105 Kir                  B300732-C
3106 Hreowan              B425278-B
3203 Maeghen              C668869-6
3205 Fluere               B765762-8
3206 Dim                  C646444-9
3207 Imkhag Guu           C567889-7
3208 Agduu                E400102-A
3210 Enkaiein             A965412-D
0112 Per                  A673410-C
0113 Khishi               C798200-A
0114 Khid                 B550401-C
0116 Idpuu                B585756-B
0117 Neki                 B664589-9
0120 Kein                 C544403-A
0212 Gir                  B645437-B
0216 Emuuis               B422369-D
0218 Darnii Kimi          D87887B-6
0220 Inir                 D88A548-9
0313 Maish Akush          B432454-C
0314 Maarshigervlig       B8A588A-A
0315 Dankahlas            B685541-B
0316 Dudin                D528A89-B
0319 Uurze                B434220-D
0411 Kash                 D584400-8
0414 Shiinaua             D561520-6
0416 Sanches              A654AC9-F
0418 Shardi               E43398A-A
0420 Nirgem               B6A7422-A
0511 Gaadir               D586836-6
0512 Arla Un              B513733-B
0513 Kaman                D772412-6
0516 Rundan               B76A945-9
0517 Shiga Sha            A726423-E
0519 Zan                  B100103-F
0612 Khukhi               B667998-A
0619 Iggaar               B7589A8-B
0713 Ruuni                B433557-D
0714 Kiishad              B6A78BD-B
0718 Uupig                D797114-7
0811 Alekvadin            B675AAB-E
0812 Kakhu Gash           A845887-A
0816 Keshi                B792566-B
0820 Iruukzi              B776610-9
0911 Kiked Iig            C545448-9
0915 Muskoxah             A577300-E
0916 Irshiish             B95A667-C
0919 Coppelia             C550154-A
1012 Uurmu Kuu            B424400-E
1016 Ushra                B561966-C
1019 Liga Ka              B783300-C
1112 Kish                 C310403-A
1114 Adguu Uun            A520834-C
1116 Vlaagesh Iirki       B783611-9
1120 Shuunkha             B5407A6-A
1214 Guun                 E585555-8
1219 Amed                 B3106B9-C
1220 Rhuan                B100122-D
1314 Mukiid               B859423-C
1316 Shiirand             D85A969-7
1317 Gipkikhar            B203462-D
1320 Adkaash              B422201-C
1416 Imdi Mi              B68A530-A
1418 Kishdush             C64648A-9
1511 Aman Urk             E545279-7
1512 Ansham               B8C3747-A
1518 Depot                A86A56A-F
1519 Sher                 D9D4665-7
1611 Shauug               B964542-B
1615 Marlakasi            B779500-C
1616 Vluurvlash           E9B4683-8
1711 N'dao                D1007B8-9
1713 Rison                B9D4695-B
1715 Fornol               B5819CA-B
1717 Curast               D9B7362-8
1812 Ances                B583757-B
1813 Lectorsen            D554765-6
1815 Thass                B510420-A
1819 Balpan               B505345-A
1912 Sistar               B430551-E
1916 Ankod                A544889-C
1917 Ploiqu               D422747-7
1918 Traak                B62488C-B
1919 Crompton             E776564-8
1920 Shion                D410344-8
2011 Dudaka               C544310-7
2012 Tiwath               E651575-7
2014 Morii                B62A644-A
2016 Ion                  B877755-B
2017 Onon                 E576321-7
2020 Tertha               C200342-B
2111 Siduka               B546689-A
2112 Romstand             C428567-9
2115 Knabbib              A431758-F
2118 Capital              A586A98-F
2211 Shushan              A655435-D
2213 Nesdo                B541231-7
2214 Shudusham            C849A55-C
2216 Rhylea               B8A6530-9
2218 Syroe                B436854-D
2219 Ase                  B42098B-E
2220 Xalm                 D5629CA-5
2312 Seku                 B79A557-E
2314 Rib                  B559767-B
2316 Ercan                B544854-A
2317 Codsen               E571568-5
2318 Yirsh Poy            B310577-B
2319 Crystalan            C979888-9
2320 Umgadin              B6B5946-C
2413 Capion               B651864-7
2414 First                AA7A888-A
2416 Sentark 4            B755596-8
2419 Sevan                A544576-B
2511 Kuuir Am             C577597-9
2513 Khuir                B89AACA-E
2517 Imaar Pa             D544433-5
2519 Riid Irman           D000330-A
2611 Kishkeiim            B201885-B
2615 Ispumer              E58197B-8
2616 Likhamii             B5368CD-9
2720 Lir                  B42647C-B
2814 Khuuma               C423669-9
2816 Indshiim Ganme       B869423-C
2912 Leer                 A7B3699-D
2913 Khiuur La            C8B3763-8
2914 Mikhag Kuu           A668973-A
2916 Khiinra Ash          BAE6362-8
3011 Laudum               B552A86-E
3015 Anuug                B783451-9
3019 Kinekesh             B422552-E
3113 Ruigiur              E542647-6
3115 Markasher            E1009CC-7
3117 Khiiri               B200456-C
3118 Lemiki               C56AA8B-D
3211 Zikhi                C427535-B
3216 Shand                B964543-9
3218 Kaskii               A300A98-F
0125 Trevor               B664410-B
0126 Deseca               B541762-A
0127 Marsus               B578598-B
0128 Protalus             B559563-C
0129 Rollabon             B984431-9
0130 Katock               E200301-A
0221 Randar               A789667-D
0222 Acmed                E310669-8
0224 Domitar              E434147-7
0228 Hektalus             B565401-B
0322 Bentax               B542275-B
0324 Oorpic               B413777-C
0325 Ikarus               B310757-D
0326 Bellum               B540401-C
0328 Ferot                B553532-B
0421 Gishalem             A887425-D
0423 Hellhole             B400555-E
0428 Irlu                 B53598C-D
0429 Relle                C9B9665-A
0522 Simic                E562554-8
0523 Dinhe                B590444-B
0526 Asalam               B200346-D
0527 Rax                  A557210-C
0529 Irdu                 B586621-A
0530 Tarshii              D433565-8
0622 Sketola              A647789-C
0624 Ontar                B100213-E
0721 Cromind              D551579-7
0722 F'rnow               B561576-B
0725 Antar                B411111-D
0727 Dral                 B728967-D
0821 Lalandra             A000322-F
0822 Dunlek               B540365-B
0827 Ess Nuur             B550400-C
0921 Wastam               E6A7777-8
0922 Celetron             A575242-F
0929 Ur                   D649577-8
1022 Drag                 D573422-7
1023 Exod                 B423555-C
1028 Shalam               C550644-8
1123 Ye-lu                A100134-F
1124 Pixtome              A8AA453-F
1125 Meman                D652552-8
1129 Gashil               C6A4511-9
1130 Evad                 C79A468-B
1221 Ehok-ta              BAD5446-A
1222 Bendo                B577975-9
1223 Dingus               D556544-7
1225 Eshon                E541766-6
1226 Orguush              A585434-D
1228 Lishiruud            B6979AA-8
1229 Digitus              D55479A-6
1321 Renu                 B66478B-8
1322 Keplo                B675998-C
1323 Bogustin             A3105AC-F
1328 Ushtar               B647554-C
1330 Calesson             B685743-9
1421 Eorvin               B436868-C
1422 Chokta               C7C2248-A
1424 Khusgurlu            B652AEG-E
1428 Spirn                A656641-C
1430 Alton                B100542-E
1522 Suhtlam              B7C2100-B
1523 Belicose             A596236-D
1524 Shibashliim          B626A8C-F
1526 Noesh                E403472-9
1529 Biirke               D310101-A
1530 Santar               B563201-C
1622 Heraldia             C420576-B
1623 Velpare              A567734-A
1625 Kirkus               B885740-A
1628 Shirg                B6337C9-B
1630 Rashiuon             B430221-D
1721 Temra                B565886-A
1724 Akeyolarix           A675546-D
1725 C're                 B545885-A
1726 Roustami             B0008AF-D
1727 Braned               B8B3411-C
1730 Waduuka              BAB5435-C
1821 Tell                 A78A472-F
1822 Holex                A200353-F
1823 Citro                E8B7333-8
1824 Mandhem              E554200-7
1825 Prempt               B5A2200-D
1829 Rhydino              B311779-C
1921 Sorca                B545740-A
1924 Tomaa                E555435-6
1925 Vvrin                A585799-C
1927 Wrebil               B94A775-8
1929 Farhome              E628544-7
1930 Traa                 A000784-F
2021 Anther               A300697-E
2027 Prubisk              B9A569A-B
2028 Basilling            A543104-E
2030 Rorpa Din            D63A566-9
2121 Affinity             B98A661-B
2122 Elinz                B576553-C
2125 Eliograh             A524575-D
2130 Kamodoo              B565658-B
2221 Leystroak            B998656-A
2222 Rek-shons            B855846-A
2223 Radd Caulo           A866745-A
2224 Chant                A560688-C
2225 Meiz                 B512847-B
2226 Skeen                B59199B-C
2227 Port Away            C557847-8
2322 Effinity             A581651-D
2323 Merat                B423868-B
2326 Akin Akun            D410666-8
2327 Drivorea             B759400-D
2330 Raami                B522966-D
2422 Ro Anii              A573420-D
2425 Avthaus              B200879-C
2429 Shurgiishulu         B552725-9
2521 Shashuua             E560463-7
2524 Glimmer              A576422-B
2526 Kisa                 A7C6320-E
2529 Udaa                 E5649A8-7
2623 Gurdaan              B3109DA-C
2624 Idas                 B5929AE-C
2625 Imsha                B424337-D
2628 Gashkanan            B74A622-A
2630 Shesh                C000314-C
2721 Kiruuda              B551686-9
2729 Gaar                 B560224-B
2730 Maan                 A541632-C
2821 Kuggar               B552997-9
2823 Berumi               C553100-A
2825 Bishaakuuka          B6839BA-8
2829 Gishashum            E100895-9
2830 Navla Sha            EAC7457-9
2922 Ekugush              B652A68-A
2924 Ushba Sind           D564879-4
2928 Vilakhu              A594300-E
2929 Danuuvlan            B000578-C
3021 Kamsii               A55788C-B
3022 Gurishi              B756A99-C
3025 Manluushagi          C200353-C
3026 Uumeshal             C563545-9
3027 Guuza Bem            B9D5769-9
3028 Durguu               A57356B-D
3121 Kagash               C5549AA-7
3123 Kankuup Ir           B4247A8-B
3125 Kadushii             D695973-8
3127 Arkadkhi             B779433-C
3128 Mish                 B679985-D
3129 Keras Vla            B867530-B
3130 Agdam Gii            B557874-A
3226 Duuka                B686576-B
3227 Ashash As            B758677-A
0132 Brygella             B76A300-E
0133 Holt                 B8D7346-C
0134 Blanum               B421677-C
0135 Erthun               B667587-B
0138 Azpun                A873411-B
0139 Dashuu Aardir        B87A220-D
0140 Reference            B100727-C
0231 Rushugim             E869472-7
0234 Zorzaa               B667520-B
0236 Tuurqa Gaash         D671443-7
0240 Brekin               B58758C-B
0331 Kiiris               E10059C-8
0332 Qungwyld             A655661-B
0334 Singing              A999310-D
0338 Markun               B887236-A
0431 Betras               B634320-C
0432 Reel                 B550779-A
0437 Lytras               B400643-B
0439 Xamdas               B310100-D
0440 Kysizi               A53A777-F
0531 Cadion               B655964-B
0537 Lia                  E654A88-A
0635 Double Star          B642652-B
0637 Patu                 B796676-8
0731 Zzugep               B553ACD-D
0734 Ferré                C797778-6
0735 Megatina             D584575-5
0737 L'rotuu              B898674-9
0831 Delta 4              C549449-A
0835 Baituu               D438110-7
0839 Night                A574AC9-F
0931 Siniir Sa            A599367-D
0933 Hudmill              B88A204-C
1033 Gavin                B556315-B
1034 Vala                 C533762-7
1035 Okefir               B581666-A
1037 Khuunish             D542201-8
1038 Maur Na              B558797-A
1040 Davla                B528200-D
1134 Aursis               A5459BD-E
1140 Kaamind              BAF5579-B
1232 Diam Kani            B430563-D
1233 Illappu              A575425-C
1236 Ishmal               B591384-B
1237 Miikuu Ar            E6A7761-8
1239 Kirbarus             B547759-B
1240 Allamu               C423304-A
1334 Anshar               BACA37B-D
1335 Umkashuu             B554AC9-D
1336 Krain                EA97596-5
1338 Prin                 B695300-C
1431 Saar                 C594446-9
1434 Diirmuu              C755303-A
1436 Arvlessaish          E6B178B-8
1437 Mirror               B9A8311-A
1440 Minduun Sammad       A58A79C-E
1531 Emsha La             C43389C-A
1533 Zagi Uun             B647886-9
1534 Gidekis              A76A651-E
1536 Shueshlar            C435998-A
1538 Ekhuurme             A5437BB-B
1539 Dimanaam             A583320-D
1633 Gandar               B300666-C
1635 Hiilev               C62757B-A
1638 Malaash              E759977-6
1732 Maasaanin            B758554-C
1733 Zimmel               B865500-C
1736 Santry               B420853-D
1737 Minamulam Kirak      B574576-B
1738 Ginna                C8A6203-B
1739 Enshuukkar           B6A6764-B
1831 Girrik               C663510-7
1833 Shaaram              D564974-8
1836 Khea                 B540955-D
1837 Anlumir              BA9A201-E
1838 Bellham              D989720-7
1839 Rilik Aash           B782555-B
1840 Saruumdiiush         E7437BC-6
1933 Kuushruu             B599775-B
1934 Zishma Kha           B886979-8
1938 Keshi                B566AD8-9
1940 Nadir                B548844-A
2034 Dindakhara           B424579-D
2036 Uundizi              A410856-F
2037 Daaud Urle           B433211-D
2038 Gimmi Uusshaa        B576550-C
2040 Khii Isis            A540745-B
2133 Degkak Uun           E88A754-9
2135 Diliig               D749121-7
2136 Kiir                 A77A5AD-F
2138 Adkhi                E88876A-6
2139 Ginnakar             B565300-C
2140 Sidzer               C20079D-A
2232 Kuuma                B538836-B
2237 Mirezi               B203212-D
2334 Bussirka             B433550-E
2335 Gish                 B555322-B
2336 Adan                 D661696-6
2338 Shinzarkan           B555720-A
2431 Kim                  D7A8678-8
2433 Uuramag              C794798-8
2435 Iidkek               BAB5423-A
2437 Ligemum              D636650-8
2439 Innameg              B584342-B
2532 Mie Duur             B310320-D
2534 Middena              B648797-8
2536 Duunpigamuur         C511637-9
2538 Duudin               B768510-B
2540 Bumina               C553414-9
2631 Uurkuumluu           B545525-A
2635 Arvlaa Gam           E889762-7
2636 Valed                B998213-B
2639 Suurashuur           B100403-E
2640 Dishadshii           B614ACG-F
2731 Milpa                B6315AF-B
2732 Shimaraak            B9E7425-C
2736 Gaen Luum            B424757-C
2832 Sinad                B558AAD-E
2836 Khuir                B578961-C
2837 Igla                 B414ADG-E
2839 Gaeshme              C783454-A
2840 Gumir Gaeg           B8C3885-B
2931 Dinenruum            E432679-6
2933 Ganad                A656ABA-F
2934 Dishe                A778332-D
2935 Amuur Keiir          C572355-A
2936 Saregon              A584A76-F
2937 Uurigger             B434779-B
2938 Shakiiga             B867ACA-C
3033 Ashmelam             A424588-F
3034 Iishaanka            A554855-D
3037 Lashupii             E665755-7
3039 Kiiggura             B8B4442-C
3040 Unlakhar             B629997-E
3131 Ashga                A7C3874-D
3132 Kinuri               B5626AC-A
3133 Nindakir             C56277B-8
3135 Arla                 B58A863-B
3137 Iimdii               B593666-9
3140 Kergumir             A562998-C
3234 Gau                  B433764-C
3235 Taliyan              B75A531-A
3238 Lishide              E560672-6

